version: '3.8'

services:
  datamap-staging-app:
    image: python:3.11
    container_name: datamap-staging-app
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    depends_on:
      - rabbitMQ
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://

  celery_worker:
    image: python:3.11
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
#    command: celery -A app.worker.celery_app worker --loglevel=info
    command: celery -A app.celery_tasks worker --loglevel=info --pool=sol
    volumes:
      - .:/app
    depends_on:
      - rabbitMQ
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://

  celery_flower:
    image: mher/flower
    container_name: celery_flower
    ports:
      - "5555:5555"
    command: >
      --broker=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitMQ

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
